version: '3'

services:
  db:
    container_name: mbtc.postgres
    image: postgres
    ports:
      - "5431:5431"
  web:
    container_name: mbtc.backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  mbtc.frontend:
    container_name: mbtc.frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run serve
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules/
    ports:
      - "8080:8080"