version: '3'

services:
  db:
    container_name: mbtc.postgres
    image: postgres
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
    - './pgdata:/var/lib/postgresql/data'
  web:
    container_name: mbtc.backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
    restart: on-failure
    command: >
      bash -c "pip install -r requirements.txt && python3 -u manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  mbtc.frontend:
    container_name: mbtc.frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: >
      bash -c "npm i && npm run serve"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules/
    ports:
      - "8080:8080"