version: '3'

services:
  db:
    container_name: mbtc.postgres
    image: postgres
    ports:
      - "5430-5450:5432"
    volumes:
    - './pgdata:/var/lib/postgresql/data'
  web:
    container_name: mbtc.backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
    command: >
      bash -c "./wait-for-it.sh db:5432 &&
      python -m venv _pyvenv &&
      source _pyvenv/bin/activate &&
      pip install -r requirements.txt &&
      python -u manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  mbtc.frontend:
    container_name: mbtc.frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: >
      bash -c "npm i && npm run serve"
    volumes:
      - ./frontend:/frontend

    ports:
      - "8080:8080"