# Generated by Django 2.1.2 on 2018-12-26 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_api', models.CharField(choices=[('google_book_api', 'Google book api')], default='google_book_api', max_length=250)),
                ('source_id', models.CharField(max_length=250)),
                ('title', models.TextField()),
                ('authors', models.TextField(blank=True, null=True)),
                ('thumbnail_link', models.TextField(blank=True, null=True)),
                ('preview_link', models.TextField(blank=True, null=True)),
                ('published_date', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
