# Generated by Django 2.1.2 on 2018-12-23 12:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181223_1128'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileImage',
            new_name='Userpic',
        ),
    ]
